# Generated by Django 6.0.4 on 2026-05-04 01:45

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon')),
                ('email', models.EmailField(default='info@bloomms.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+966 55 123 4567', max_length=50, verbose_name='Phone')),
                ('whatsapp', models.CharField(default='+966 55 123 4567', max_length=50, verbose_name='WhatsApp')),
                ('address', models.TextField(default='Riyadh, Saudi Arabia', verbose_name='Address')),
                ('map_link', models.URLField(blank=True, verbose_name='Map Link')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('stats_projects', models.PositiveIntegerField(default=150, verbose_name='Projects Completed')),
                ('stats_clients', models.PositiveIntegerField(default=80, verbose_name='Happy Clients')),
                ('stats_years', models.PositiveIntegerField(default=5, verbose_name='Years Experience')),
                ('stats_team', models.PositiveIntegerField(default=25, verbose_name='Team Members')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('company_name', models.CharField(default='Bloom Microservice', max_length=200, verbose_name='Company Name')),
                ('tagline', models.CharField(default='Premium Microservices & Software Solutions', max_length=300, verbose_name='Tagline')),
                ('description', models.TextField(default='Bloom Microservice is a leading software development agency specializing in modern web applications, microservices architecture, and enterprise solutions.', verbose_name='Description')),
                ('hero_title', models.CharField(default='Building Digital Excellence', max_length=300, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(default='We craft cutting-edge software solutions and microservices that transform your business.', verbose_name='Hero Subtitle')),
                ('hero_cta_text', models.CharField(default='Start Your Project', max_length=100, verbose_name='Hero CTA Text')),
                ('hero_cta_link', models.URLField(default='/en/contact/', verbose_name='Hero CTA Link')),
                ('about_title', models.CharField(default='About Bloom Microservice', max_length=300, verbose_name='About Title')),
                ('about_content', models.TextField(default='Bloom Microservice is a premier software development company founded in 2020. We specialize in delivering high-quality web applications, mobile apps, and enterprise software solutions tailored to meet the unique needs of our clients.', verbose_name='About Content')),
                ('cta_title', models.CharField(default='Ready to Transform Your Business?', max_length=300, verbose_name='CTA Title')),
                ('cta_content', models.TextField(default="Let's discuss your project and build something amazing together.", verbose_name='CTA Content')),
                ('cta_button', models.CharField(default='Get a Quote', max_length=100, verbose_name='CTA Button')),
                ('working_hours', models.CharField(default='Sunday - Thursday: 9:00 AM - 6:00 PM', max_length=200, verbose_name='Working Hours')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Site Settings Translation',
                'db_table': 'core_sitesettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
