# Generated by Django 6.0.4 on 2026-05-04 01:45

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('lang', models.CharField(default='en', max_length=5, verbose_name='Language')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Replied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('default', 'Default'), ('home', 'Home'), ('about', 'About'), ('services', 'Services List'), ('service_detail', 'Service Detail'), ('projects', 'Projects List'), ('project_detail', 'Project Detail'), ('contact', 'Contact'), ('blog', 'Blog'), ('blog_detail', 'Blog Detail')], default='default', max_length=100, verbose_name='Template')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Cover Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured in Menu')),
                ('in_footer', models.BooleanField(default=False, verbose_name='Show in Footer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], max_length=20, verbose_name='Position')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Label')),
                ('order', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(blank=True, help_text='Custom URL (optional)', max_length=300)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='pages.page')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=300, verbose_name='Page Title')),
                ('heading', models.CharField(blank=True, max_length=300, verbose_name='Heading')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Translation',
                'db_table': 'pages_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
