# Generated by Django 6.0.4 on 2026-05-09 10:10

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttranslation',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Content'),
        ),
    ]
